#!/usr/bin/env node

/*
 * Rebuild the compiled Obsidian display resources.
 *
 * This script deliberately uses the same review wrapper that was used for the
 * approved preview.  It waits for liquid-glass-react to install, fixes the
 * face scale at 1, removes only text/glyphs and active SVG paths/endcaps, and
 * captures the resulting .stage at its native 466 x 466 CSS pixels.
 *
 * Required runtime dependencies are supplied by the Codex workspace runtime:
 *
 *   NODE_PATH=/path/to/node_modules PLAYWRIGHT_CHROMIUM=/path/to/chromium \
 *     node tools/generate_assets.cjs
 *
 * lv_font_conv is intentionally invoked through a pinned npm version.  The
 * browser executable can be overridden with PLAYWRIGHT_CHROMIUM when the
 * pinned workspace browser is unavailable.
 */

'use strict';

const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL } = require('node:url');
const { spawnSync } = require('node:child_process');
const { chromium } = require('playwright');
const sharp = require('sharp');
const { PNG } = require('pngjs');

const ROOT = path.resolve(__dirname, '..');
const SOURCE = path.join(ROOT, 'source');
const LV_FONT_CONV_VERSION = '1.5.3';
const FACE = 466;
const GLYPH = 18;
const NUMERIC_SYMBOLS = '.-0123456789KMBT';

function argValue(name, fallback) {
  const index = process.argv.indexOf(name);
  return index === -1 ? fallback : process.argv[index + 1];
}

function fail(message) {
  throw new Error(message);
}

function assertFile(file, description) {
  if (!fs.existsSync(file)) fail(`${description} does not exist: ${file}`);
}

function rgb565(red, green, blue) {
  // LVGL's RGB565 image data is native-endian.  ESP32-S3 is little-endian,
  // so emit the low byte before the high byte for each packed pixel.
  const packed = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3);
  return [packed & 0xff, packed >> 8];
}

function writeByteArray(file, symbol, bytes, descriptor) {
  const lines = [];
  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(`  ${Array.from(bytes.slice(index, index + 16))
      .map((value) => `0x${value.toString(16).padStart(2, '0')}`)
      .join(', ')},`);
  }
  const text = `/* Generated by tools/generate_assets.cjs; do not edit by hand. */
#include <stdint.h>

#include "obsidian_assets.h"

static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST const uint8_t ${symbol}_map[] = {
${lines.join('\n')}
};

const lv_image_dsc_t ${symbol} = {
  .header.magic = LV_IMAGE_HEADER_MAGIC,
  .header.cf = ${descriptor.format},
  .header.flags = 0,
  .header.w = ${descriptor.width},
  .header.h = ${descriptor.height},
  .header.stride = ${descriptor.stride},
  .data_size = sizeof(${symbol}_map),
  .data = ${symbol}_map,
};
`;
  fs.writeFileSync(file, text);
}

function parseHexColor(value) {
  const clean = value.replace(/^#/, '');
  return [
    parseInt(clean.slice(0, 2), 16),
    parseInt(clean.slice(2, 4), 16),
    parseInt(clean.slice(4, 6), 16),
  ];
}

function sampleStops(stops, position) {
  if (position <= stops[0][0]) return stops[0][1];
  for (let index = 1; index < stops.length; index += 1) {
    if (position <= stops[index][0]) {
      const [leftPosition, leftColor] = stops[index - 1];
      const [rightPosition, rightColor] = stops[index];
      const amount = (position - leftPosition) / (rightPosition - leftPosition);
      return leftColor.map((component, channel) =>
        Math.round(component + (rightColor[channel] - component) * amount),
      );
    }
  }
  return stops[stops.length - 1][1];
}

function gradientBytes(stopDefinitions) {
  const stops = stopDefinitions.map(([position, color]) => [position, parseHexColor(color)]);
  const bytes = Buffer.alloc(FACE * FACE * 2);
  let offset = 0;
  for (let y = 0; y < FACE; y += 1) {
    for (let x = 0; x < FACE; x += 1) {
      // SVG's x1=0,y1=0,x2=1,y2=1 gradient is evaluated in sRGB.  A
      // face-wide x/y coordinate keeps the provider color stable when the
      // native renderer masks any point on the full ring circumference.
      const position = (x + y) / (2 * (FACE - 1));
      const [red, green, blue] = sampleStops(stops, position);
      const [low, high] = rgb565(red, green, blue);
      bytes[offset++] = low;
      bytes[offset++] = high;
    }
  }
  return bytes;
}

function escapeAttribute(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function standaloneWrapper(previewHtml) {
  // Keep the source fragment in the component while reproducing the review
  // iframe boundary in memory.  An explicit --wrapper remains available for
  // using a captured app wrapper byte-for-byte.
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body style="margin:0;background:#000"><iframe sandbox="allow-scripts" referrerpolicy="no-referrer" title="Pocket Code Liquid Studio" style="display:block;width:100%;height:100vh;border:0" srcdoc="${escapeAttribute(previewHtml)}"></iframe></body></html>`;
}

async function captureBackground(preview, wrapper) {
  if (wrapper) assertFile(wrapper, 'preview wrapper');
  assertFile(preview, 'approved preview fragment');
  const executablePath = process.env.PLAYWRIGHT_CHROMIUM || chromium.executablePath();
  assertFile(executablePath, 'Playwright Chromium executable');
  const browser = await chromium.launch({ executablePath, headless: true });
  try {
    const page = await browser.newPage({
      viewport: { width: 1000, height: 850 },
      deviceScaleFactor: 1,
      colorScheme: 'dark',
      reducedMotion: 'reduce',
    });
    if (wrapper) {
      await page.goto(pathToFileURL(wrapper).href, { waitUntil: 'domcontentloaded' });
    } else {
      await page.setContent(standaloneWrapper(fs.readFileSync(preview, 'utf8')), {
        waitUntil: 'domcontentloaded',
      });
    }
    const frameLocator = page.frameLocator('iframe');
    await frameLocator
      .locator('#pc-liquid-studio[data-engine="liquid-glass-react"]')
      .waitFor({ state: 'attached', timeout: 30000 });

    const frame = page.frames().find((candidate) => candidate !== page.mainFrame());
    if (!frame) fail('preview iframe did not create a child frame');
    await frame.waitForFunction(
      () => document.querySelector('#pc-liquid-studio[data-engine="liquid-glass-react"]'),
      null,
      { timeout: 30000 },
    );

    await frame.evaluate(() => {
      const root = document.querySelector('#pc-liquid-studio');
      const stage = root.querySelector('.stage');
      if (!root || !stage) throw new Error('preview stage is missing');

      // The element screenshot includes the page behind rounded corners.  A
      // black page makes those pixels opaque black in the final RGB565 face.
      document.documentElement.style.setProperty('background', '#000', 'important');
      document.body.style.setProperty('background', '#000', 'important');

      stage.style.setProperty('--pc-fit', '1');
      stage.querySelectorAll('#pcs-rings path').forEach((element) => {
        element.style.display = 'none';
      });
      stage.querySelectorAll('#pcs-rings circle').forEach((element) => {
        if (element.getAttribute('stroke') !== 'url(#pcs-track)') {
          element.style.display = 'none';
        }
      });
      // Keep the React LiquidGlass lens itself while removing every label,
      // number, provider name, and alpha glyph from its content layer.
      stage.querySelectorAll('.lens-content, .lens-content *').forEach((element) => {
        element.style.visibility = 'hidden';
        element.setAttribute('aria-hidden', 'true');
      });
      stage.querySelector('#pcs-sweep').style.display = 'none';
    });

    // Allow LiquidGlass's measured filter/canvas dimensions to settle after
    // the scale and visibility changes (the review wrapper can measure twice).
    await frame.evaluate(
      () =>
        new Promise((resolve) =>
          requestAnimationFrame(() => requestAnimationFrame(() => requestAnimationFrame(resolve))),
        ),
    );

    const stage = frame.locator('.stage');
    const box = await stage.boundingBox();
    if (!box || box.width !== FACE || box.height !== FACE) {
      fail(`stage was not captured at scale 1: ${JSON.stringify(box)}`);
    }
    const png = PNG.sync.read(await stage.screenshot({ omitBackground: false }));
    if (png.width !== FACE || png.height !== FACE) {
      fail(`stage screenshot dimensions were ${png.width}x${png.height}`);
    }

    // Enforce the opaque square contract outside the circular face.  The
    // browser already composites the border-radius edge over black; this
    // explicit pass guards against future wrapper background changes.
    const center = (FACE - 1) / 2;
    for (let y = 0; y < FACE; y += 1) {
      for (let x = 0; x < FACE; x += 1) {
        if (Math.hypot(x - center, y - center) > center) {
          const pixel = (y * FACE + x) * 4;
          png.data[pixel] = 0;
          png.data[pixel + 1] = 0;
          png.data[pixel + 2] = 0;
          png.data[pixel + 3] = 255;
        }
      }
    }
    return png;
  } finally {
    await browser.close();
  }
}

async function glyphAlpha(sourceFile) {
  const svg = fs.readFileSync(sourceFile);
  const rendered = await sharp(svg)
    .resize(GLYPH, GLYPH, { fit: 'fill' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const alpha = Buffer.alloc(GLYPH * GLYPH);
  for (let index = 0; index < alpha.length; index += 1) {
    alpha[index] = rendered.data[index * rendered.info.channels + rendered.info.channels - 1];
  }
  return alpha;
}

function generateFonts() {
  const numeric = [
    ['pc_inter_64.c', 'pc_inter_64', '64'],
    ['pc_inter_84.c', 'pc_inter_84', '84'],
    ['pc_inter_34.c', 'pc_inter_34', '34'],
  ];
  const ascii = [
    ['pc_inter_22.c', 'pc_inter_22', '22'],
    ['pc_inter_18.c', 'pc_inter_18', '18'],
    ['pc_inter_17.c', 'pc_inter_17', '17'],
    ['pc_inter_14.c', 'pc_inter_14', '14'],
    ['pc_inter_11.c', 'pc_inter_11', '11'],
  ];
  for (const [filename, name, size] of [...numeric, ...ascii]) {
    const args = [
      '--yes',
      `lv_font_conv@${LV_FONT_CONV_VERSION}`,
      '--font',
      'source/Inter-Regular.ttf',
      '--size',
      size,
      '--bpp',
      '4',
      '--format',
      'lvgl',
      '--lv-include',
      'lvgl.h',
      '--lv-font-name',
      name,
    ];
    if (numeric.some((entry) => entry[1] === name)) {
      args.push('--symbols', NUMERIC_SYMBOLS);
    } else {
      args.push('--range', '0x20-0x7E');
    }
    // The ESP-IDF image keeps LV_USE_FONT_COMPRESSED disabled.  Emit plain
    // bitmap rows so these generated fonts work with the maintained sdkconfig.
    args.push('--no-compress', '--output', filename);
    const result = spawnSync('npx', args, {
      cwd: ROOT,
      stdio: 'inherit',
      env: process.env,
    });
    if (result.error) throw result.error;
    if (result.status !== 0) fail(`lv_font_conv failed for ${name} with status ${result.status}`);
  }
}

async function main() {
  const preview = path.resolve(argValue('--preview', path.join(SOURCE, 'pocket-code-liquid-studio.html')));
  const wrapperArg = argValue('--wrapper', null);
  const wrapper = wrapperArg ? path.resolve(wrapperArg) : null;
  const previewPng = await captureBackground(preview, wrapper);
  const background = Buffer.alloc(FACE * FACE * 2);
  for (let index = 0; index < FACE * FACE; index += 1) {
    const source = index * 4;
    const destination = index * 2;
    const [low, high] = rgb565(
      previewPng.data[source],
      previewPng.data[source + 1],
      previewPng.data[source + 2],
    );
    background[destination] = low;
    background[destination + 1] = high;
  }
  writeByteArray(path.join(ROOT, 'obsidian_background.c'), 'pc_obsidian_background', background, {
    format: 'LV_COLOR_FORMAT_RGB565',
    width: 'PC_OBSIDIAN_FACE_WIDTH',
    height: 'PC_OBSIDIAN_FACE_HEIGHT',
    stride: 'PC_OBSIDIAN_FACE_STRIDE',
  });

  const gradients = [
    [
      'pc_ring_codex',
      [
        [0, '#c4edff'],
        [0.22, '#8ac7ff'],
        [0.55, '#4c96e4'],
        [1, '#82bcea'],
      ],
    ],
    [
      'pc_ring_claude',
      [
        [0, '#f8dfcc'],
        [0.28, '#eabc9f'],
        [0.62, '#be8669'],
        [1, '#efd0b5'],
      ],
    ],
    [
      'pc_ring_grok',
      [
        [0, '#f1f8ff'],
        [0.55, '#b9ccdf'],
        [1, '#7e95ad'],
      ],
    ],
  ];
  const gradientBytesByName = gradients.map(([name, stops]) => [name, gradientBytes(stops)]);
  const gradientParts = gradientBytesByName.map(([name, bytes]) => {
    const lines = [];
    for (let index = 0; index < bytes.length; index += 16) {
      lines.push(`  ${Array.from(bytes.slice(index, index + 16))
        .map((value) => `0x${value.toString(16).padStart(2, '0')}`)
        .join(', ')},`);
    }
    return `static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST const uint8_t ${name}_map[] = {\n${lines.join('\n')}\n};\n\nconst lv_image_dsc_t ${name} = {\n  .header.magic = LV_IMAGE_HEADER_MAGIC,\n  .header.cf = LV_COLOR_FORMAT_RGB565,\n  .header.flags = 0,\n  .header.w = PC_OBSIDIAN_FACE_WIDTH,\n  .header.h = PC_OBSIDIAN_FACE_HEIGHT,\n  .header.stride = PC_OBSIDIAN_FACE_STRIDE,\n  .data_size = sizeof(${name}_map),\n  .data = ${name}_map,\n};`;
  });
  fs.writeFileSync(
    path.join(ROOT, 'ring_gradients.c'),
    `/* Generated by tools/generate_assets.cjs; do not edit by hand. */\n#include <stdint.h>\n\n#include "obsidian_assets.h"\n\n${gradientParts.join('\n\n')}\n`,
  );

  const glyphs = [
    ['pc_glyph_codex', 'openai.svg'],
    ['pc_glyph_claude', 'claude.svg'],
    ['pc_glyph_grok', 'grok.svg'],
  ];
  const glyphParts = [];
  for (const [name, filename] of glyphs) {
    const bytes = await glyphAlpha(path.join(SOURCE, 'icons', filename));
    const lines = [];
    for (let index = 0; index < bytes.length; index += 18) {
      lines.push(`  ${Array.from(bytes.slice(index, index + 18))
        .map((value) => `0x${value.toString(16).padStart(2, '0')}`)
        .join(', ')},`);
    }
    glyphParts.push(`static LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST const uint8_t ${name}_map[] = {\n${lines.join('\n')}\n};\n\nconst lv_image_dsc_t ${name} = {\n  .header.magic = LV_IMAGE_HEADER_MAGIC,\n  .header.cf = LV_COLOR_FORMAT_A8,\n  .header.flags = 0,\n  .header.w = PC_OBSIDIAN_GLYPH_WIDTH,\n  .header.h = PC_OBSIDIAN_GLYPH_HEIGHT,\n  .header.stride = PC_OBSIDIAN_GLYPH_STRIDE,\n  .data_size = sizeof(${name}_map),\n  .data = ${name}_map,\n};`);
  }
  fs.writeFileSync(
    path.join(ROOT, 'provider_glyphs.c'),
    `/* Generated by tools/generate_assets.cjs; do not edit by hand. */\n#include <stdint.h>\n\n#include "obsidian_assets.h"\n\n${glyphParts.join('\n\n')}\n`,
  );

  generateFonts();
  console.log(`Generated Obsidian background, provider textures, glyphs, and ${8} Inter subsets.`);
}

main().catch((error) => {
  console.error(error.stack || error);
  process.exitCode = 1;
});
